"""Describe your changes here

Revision ID: 80d1e00f622a
Revises: 67c6b491714b
Create Date: 2026-06-30 13:46:22.410885

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '80d1e00f622a'
down_revision: str | None = '67c6b491714b'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
